/**
 * Job Seeker Keywords for TheNetwrk Extension
 * Comprehensive keywords used to identify potential job seekers and career changers
 */

window.JOB_SEEKER_KEYWORDS = {
  // Direct job seeking signals
  jobSeeking: [
    'open to work',
    'looking for work',
    'seeking opportunities',
    'job search',
    'actively looking',
    'available for hire',
    'open to new opportunities',
    'currently seeking',
    'job hunting',
    'looking for a new role',
    'seeking employment',
    'open for work',
    'available immediately',
    'ready to start',
    'exploring opportunities',
    'interested in new roles',
    'accepting offers',
    'open to offers',
    'looking for my next',
    'seeking new challenges',
    'ready for new opportunity',
    'open to discussing',
    'considering new roles',
    'exploring new positions',
    'open to remote work',
    'seeking remote opportunities',
    'looking for remote roles',
    'open to relocation',
    'willing to relocate',
    'seeking full-time',
    'seeking part-time',
    'looking for contract',
    'open to freelance',
    'seeking consulting work'
  ],

  // Career transition signals
  careerChange: [
    'career change',
    'career transition',
    'switching careers',
    'pivoting to tech',
    'breaking into tech',
    'transitioning to',
    'changing careers',
    'new career path',
    'career pivot',
    'moving into tech',
    'entering tech field',
    'tech transition',
    'shifting to tech',
    'tech career change',
    'becoming a developer',
    'switching to software',
    'moving to data',
    'transitioning from',
    'leaving my current field',
    'exploring tech roles',
    'interested in tech',
    'passionate about tech',
    'drawn to technology',
    'fascinated by coding',
    'excited about programming',
    'ready for tech challenge',
    'tech enthusiast',
    'aspiring developer',
    'future programmer',
    'wannabe coder',
    'tech curious',
    'coding journey'
  ],

  // Education/Learning signals
  learning: [
    'bootcamp graduate',
    'coding bootcamp',
    'self taught',
    'learning to code',
    'studying programming',
    'new to programming',
    'junior developer',
    'entry level',
    'recent graduate',
    'looking to learn',
    'career changer',
    'upskilling',
    'reskilling',
    'learning javascript',
    'learning python',
    'learning react',
    'studying computer science',
    'taking online courses',
    'completing certification',
    'finished bootcamp',
    'graduated from',
    'completed program',
    'self-taught developer',
    'autodidact',
    'continuous learner',
    'lifelong learner',
    'skill development',
    'professional development',
    'expanding skillset',
    'building portfolio',
    'working on projects',
    'side projects',
    'personal projects',
    'github portfolio',
    'coding challenges',
    'hackathon participant',
    'open source contributor',
    'learning journey',
    'coding bootcamp alumni',
    'certificate holder',
    'recently certified',
    'new skills',
    'fresh knowledge',
    'modern stack',
    'latest technologies'
  ],

  // Unemployment/availability signals
  availability: [
    'unemployed',
    'between jobs',
    'recently laid off',
    'looking for my next',
    'available for hire',
    'ready to start',
    'immediate availability',
    'notice period',
    'last day',
    'finishing up',
    'contract ending',
    'seeking new challenges',
    'currently unemployed',
    'out of work',
    'job loss',
    'company closure',
    'downsizing',
    'restructuring',
    'position eliminated',
    'contract expired',
    'project completed',
    'freelancing',
    'consulting',
    'temporary work',
    'interim role',
    'gap year',
    'sabbatical',
    'taking a break',
    'career break',
    'family leave',
    'personal time',
    'ready to return',
    'back to work',
    'returning to workforce',
    'career restart',
    'fresh start',
    'new beginning'
  ],

  // Tech-specific signals
  techInterest: [
    'learning javascript',
    'learning python',
    'learning react',
    'web development',
    'software development',
    'frontend developer',
    'backend developer',
    'full stack',
    'data science',
    'machine learning',
    'cybersecurity',
    'cloud computing',
    'devops',
    'mobile development',
    'ios development',
    'android development',
    'game development',
    'ai development',
    'blockchain',
    'cryptocurrency',
    'fintech',
    'edtech',
    'healthtech',
    'saas',
    'startup',
    'tech startup',
    'software engineer',
    'programmer',
    'coder',
    'developer',
    'data analyst',
    'data scientist',
    'ux designer',
    'ui designer',
    'product manager',
    'scrum master',
    'agile',
    'tech lead',
    'engineering manager',
    'solution architect',
    'system administrator',
    'database administrator',
    'network engineer',
    'security analyst',
    'qa engineer',
    'test engineer',
    'automation engineer',
    'site reliability engineer'
  ],

  // Industry transition signals
  industryTransition: [
    'leaving finance',
    'leaving healthcare',
    'leaving education',
    'leaving retail',
    'leaving hospitality',
    'leaving manufacturing',
    'leaving government',
    'leaving non-profit',
    'leaving consulting',
    'leaving law',
    'leaving marketing',
    'leaving sales',
    'from traditional industry',
    'corporate background',
    'business background',
    'non-tech background',
    'different industry',
    'industry switch',
    'sector change',
    'field transition',
    'domain expertise',
    'transferable skills',
    'cross-functional',
    'interdisciplinary',
    'diverse background',
    'unique perspective',
    'bringing experience from',
    'applying skills to tech',
    'leveraging background in'
  ],

  // Emotional/motivational signals
  motivation: [
    'passionate about',
    'excited about',
    'motivated by',
    'driven by',
    'inspired by',
    'fascinated by',
    'curious about',
    'enthusiastic about',
    'eager to learn',
    'ready to grow',
    'ambitious',
    'determined',
    'committed to',
    'dedicated to',
    'focused on',
    'goal-oriented',
    'results-driven',
    'problem solver',
    'creative thinker',
    'innovative mindset',
    'growth mindset',
    'continuous improvement',
    'always learning',
    'never stop learning',
    'love challenges',
    'thrive under pressure',
    'enjoy problem solving',
    'analytical thinking',
    'logical approach',
    'detail-oriented',
    'team player',
    'collaborative',
    'communication skills',
    'leadership potential',
    'mentorship interest',
    'teaching others',
    'knowledge sharing'
  ],

  // Timeline indicators
  timeline: [
    'immediately available',
    'available now',
    'can start immediately',
    'two weeks notice',
    '30 days notice',
    'flexible start date',
    'negotiable start date',
    'end of month',
    'beginning of year',
    'new year resolution',
    'quarterly goal',
    'annual goal',
    'next chapter',
    'next phase',
    'next step',
    'time for change',
    'ready for change',
    'change is good',
    'embracing change',
    'new adventure',
    'fresh start',
    'clean slate',
    'turning point',
    'milestone',
    'achievement unlocked',
    'level up',
    'upgrade career',
    'career advancement',
    'professional growth',
    'skill enhancement',
    'capability building'
  ],

  // Location/remote work signals
  location: [
    'remote work',
    'work from home',
    'distributed team',
    'location independent',
    'digital nomad',
    'flexible location',
    'open to remote',
    'remote first',
    'remote friendly',
    'hybrid work',
    'flexible schedule',
    'work-life balance',
    'family time',
    'personal time',
    'flexible hours',
    'part-time',
    'contract work',
    'freelance',
    'consulting',
    'project-based',
    'gig economy',
    'side hustle',
    'multiple income streams',
    'portfolio career',
    'diverse projects',
    'variety in work',
    'different challenges',
    'new environments',
    'travel opportunities',
    'global team',
    'international experience',
    'cross-cultural',
    'multicultural team'
  ],

  // Negative keywords (exclude these)
  exclude: [
    'not looking',
    'happy in current role',
    'not interested',
    'content where I am',
    'recently started',
    'just joined',
    'love my job',
    'not seeking',
    'satisfied with current',
    'staying put',
    'committed to current',
    'loyal to company',
    'long-term position',
    'stable role',
    'permanent position',
    'not changing',
    'no interest in',
    'closed to opportunities',
    'fully booked',
    'capacity reached',
    'unavailable',
    'on sabbatical',
    'taking break from work',
    'retired',
    'semi-retired',
    'not working',
    'student only',
    'full-time student',
    'academic focus',
    'research only',
    'not job seeking',
    'career pause',
    'family focus',
    'personal projects only'
  ],

  // Confidence levels for scoring
  confidence: {
    high: ['open to work', 'actively looking', 'seeking opportunities', 'job search', 'unemployed', 'laid off'],
    medium: ['career change', 'transitioning', 'exploring opportunities', 'bootcamp graduate', 'learning to code'],
    low: ['passionate about', 'interested in', 'curious about', 'excited about']
  },

  // Industry-specific keywords
  industries: {
    fintech: ['fintech', 'financial technology', 'banking tech', 'payment systems', 'cryptocurrency', 'blockchain'],
    healthtech: ['healthtech', 'medical technology', 'digital health', 'telemedicine', 'health apps'],
    edtech: ['edtech', 'educational technology', 'online learning', 'e-learning', 'digital education'],
    ecommerce: ['ecommerce', 'online retail', 'digital commerce', 'marketplace', 'shopping platforms'],
    saas: ['saas', 'software as a service', 'cloud software', 'subscription software', 'b2b software'],
    gaming: ['gaming', 'game development', 'mobile games', 'console games', 'vr games', 'ar games'],
    ai: ['artificial intelligence', 'machine learning', 'deep learning', 'neural networks', 'nlp', 'computer vision'],
    cybersecurity: ['cybersecurity', 'information security', 'network security', 'data protection', 'ethical hacking']
  }
};

console.log('✅ Comprehensive Job Seeker Keywords loaded - 400+ keywords across 10+ categories');
